server:
  address: localhost
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.213.129:3306/ccm?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/ccm?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
#    username: root
    password: teamBEP0
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      idleTimeout: 300000

app:
  language:
    default: ja
  datetime:
    format: yyyy/MM/dd HH:mm
  log:
    filepath: logs/

taskexecutor:
  corepoolsize: 4
  queuecapacity: 16
  maxpoolsize: 16
