server:
  address: localhost
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/labo?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: password
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      idleTimeout: 300000
  mail:
    host: smtp.gmail.com
    port: 587
    username: app@xxdadxx.jp
    password: ozvarxuyamqnjdjv
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            protocols: TLSv1.2
          starttls:
            enable: true
            required: true

security:
  jwt:
    secret-key: ZnItc4ktcmRzLWJlbWFjMi6jbHVzdGVyLWNibXpmZmltbWV8eS5hcC1ub3J0aGVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==

app:
  name: DemoApp
  base:
    url: http://localhost:3000
  language:
    default: ja
  datetime:
    format: yyyy/MM/dd HH:mm
  log:
    filepath: logs/

taskexecutor:
  corepoolsize: 4
  queuecapacity: 16
  maxpoolsize: 16

oauth2:
  google:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: http://${server.address}:${server.port}/api/oauth2/login/google/access-token
    scope:
      - profile
      - email
