server:
  address: 127.0.0.1
  port: 8080
  viewport: 80
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://smoothilab-db.c52wkug8qkp2.ap-northeast-2.rds.amazonaws.com:3306/public?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: smoothilab2024
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      idleTimeout: 300000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: smoothilab@gmail.com
    password: ozvarxuyamqnjdjv
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            protocols: TLSv1.2
          starttls:
            enable: true
            required: true

security:
  oauth2:
    base: https://smoothilab.com
  jwt:
    secret-key: ZnItc4ktcmRzLWJlbWFjMi6jbHVzdGVyLWNibXpmZmltbWV8eS5hcC1ub3J0aGVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==

app:
  name: Smoothilab
  base:
    url: https://smoothilab.com
  language:
    default: ja
  datetime:
    format: yyyy/MM/dd HH:mm
  log:
    filepath: logs/

taskexecutor:
  corepoolsize: 4
  queuecapacity: 16
  maxpoolsize: 16

cloud:
  aws:
    credentials:
      accessKey: AKIAYIWFETD7TIS4W2GZ
      secretKey: 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
    region:
      auto: false
      static: ap-northeast-1
    s3:
      bucketName: smoothilab
      prefix:
        user: user
        products: products

oauth2:
  google:
    client-id: 15620733964-4tug513u4ht9djhlvbaikilk4o9prh5r.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: ${security.oauth2.base}/login/oauth2/google
  line:
    client-id: 2002740571
    client-secret: 98888150aea712e2f4aaa044cfeda53f
    redirect-uri: ${security.oauth2.base}/login/oauth2/line
