server:
  address: 127.0.0.1
  port: 8080
  viewport: 80
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dad-db-instance.chgxokrx4m2o.ap-northeast-1.rds.amazonaws.com:3306/labo?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: labo
    password: HIAYeOVu4nbGjRbOeK6N
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      idleTimeout: 300000
  mail:
    host: smtp.gmail.com
    port: 587
    username: app@xxdadxx.jp
    password: ozvarxuyamqnjdjv
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            protocols: TLSv1.2
          starttls:
            enable: true
            required: true

security:
  oauth2:
    base: https://dad-labo.com
  jwt:
    secret-key: ZnItc4ktcmRzLWJlbWFjMi6jbHVzdGVyLWNibXpmZmltbWV8eS5hcC1ub3J0aGVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==

app:
  name: DemoApp
  base:
    url: https://dad-labo.com
  language:
    default: ja
  datetime:
    format: yyyy/MM/dd HH:mm
  log:
    filepath: logs/

taskexecutor:
  corepoolsize: 4
  queuecapacity: 16
  maxpoolsize: 16

oauth2:
  google:
    client-id: 1088998722997-ri0asd6o1gpbj6djenc5lej8ce7n2f37.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: ${security.oauth2.base}/login/oauth2/google
  line:
    client-id: 2000050381
    client-secret: fadbacadfbc26f6e3451de989c39bf0d
    redirect-uri: ${security.oauth2.base}/login/oauth2/line
