server:
  address: localhost
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dad-db-instance.chgxokrx4m2o.ap-northeast-1.rds.amazonaws.com:3306/labo?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: labo
    password: HIAYeOVu4nbGjRbOeK6N
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      idleTimeout: 300000

security:
  jwt:
    secret-key: ZnItc4ktcmRzLWJlbWFjMi6jbHVzdGVyLWNibXpmZmltbWV8eS5hcC1ub3J0aGVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==

app:
  language:
    default: ja
  datetime:
    format: yyyy/MM/dd HH:mm
  log:
    filepath: logs/

taskexecutor:
  corepoolsize: 4
  queuecapacity: 16
  maxpoolsize: 16
